# Generated by Django 3.0.7 on 2020-07-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200701_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
