# Generated by Django 3.0.7 on 2020-07-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='msg_id',
        ),
    ]
