# Generated by Django 3.0.7 on 2020-07-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200714_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='json_order',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
