# Generated by Django 3.0.7 on 2020-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_checkout_json_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='', max_length=30)),
                ('updated_desc', models.CharField(default='', max_length=300)),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
