# Generated by Django 3.0.7 on 2020-07-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200716_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
