# Generated by Django 3.0.7 on 2020-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
